import streamlit as st
import yfinance as yf
import datetime

# ==================== 基本設定 ====================
st.set_page_config(
    page_title="風險執行計算器",
    page_icon="⚔️",
    layout="wide",
    initial_sidebar_state="collapsed"
)

# ==================== 多語言支援 ====================
if 'language' not in st.session_state:
    st.session_state.language = "zh-tw"

trans = {
    "zh-tw": {
        "title": "⚔️ 風險執行計算器",
        "caption": "版本：雙雷達 (股價 + 實時外匯) 連動版",
        "funds_title": "💰 資金與標的",
        "exchange_label": "🔄 美金/馬幣 即時匯率",
        "system_fetch": " (系統抓取: {})",
        "watchlist_label": "📋 專屬軍火庫 (可打字搜尋)",
        "manual_input": "手動輸入",
        "ticker_label": "標的代號 (Ticker)",
        "platform_label": "交易平台",
        "moomoo_option": "Moomoo (MY)",
        "new_user_promo": "新用戶 180 天免佣",
        "usd_budget_label": "投入總預算 (USD)",
        "myr_budget_label": "投入總預算 (MYR)",
        "buy_price_label": "打算進場的價格 (USD)",
        "quantity_label": "最終確認購買股數",
        "max_quantity_hint": "最多可買",
        "percent_title": "🎯 戰術百分比 (%) 設定",
        "profit_slider": "📈 基準獲利目標 (%)",
        "stoploss_slider": "📉 基準停損底線 (%)",
        "take_profit_header": "獲利劇本 (Take Profit)",
        "stop_loss_header": "防禦劇本 (Stop Loss)",
        "scheme_a": "A 方案: 保守",
        "scheme_b": "B 方案: 達標",
        "scheme_c": "C 方案: 延伸",
        "stop_a": "A 方案: 撤退",
        "stop_b": "B 方案: 標準",
        "stop_c": "C 方案: 極限",
        "target_price": "目標價",
        "trigger_price": "觸發價",
        "net_profit": "淨賺",
        "net_loss": "淨虧",
        "budget_warning": "⚠️ 預算不足以購買 1 股並支付手續費。",
        "quote_time": "⏱️ 報價時間: {}",
        "execution_title": "實行數據：",
        "input_label": "投入：",
        "purchase_label": "購買 ：",
        "remaining_label": "剩餘資金:",
        "disclaimer": "**免責聲明**：本工具僅供參考，不構成任何投資建議。過去表現不代表未來結果。本計算機僅為輔助工具，所有數據及計算結果僅供參考，請自行判斷風險並承擔一切後果。"
    },
    "zh-cn": {  # 簡中同步
        "title": "⚔️ 风险执行计算器",
        "caption": "版本：双雷达 (股价 + 实时外汇) 联动版",
        "funds_title": "💰 资金与标的",
        "exchange_label": "🔄 美元/马币 实时汇率",
        "system_fetch": " (系统抓取: {})",
        "watchlist_label": "📋 专属军火库 (可打字搜索)",
        "manual_input": "手动输入",
        "ticker_label": "标的代码 (Ticker)",
        "platform_label": "交易平台",
        "moomoo_option": "Moomoo (MY)",
        "new_user_promo": "新用户 180 天免佣",
        "usd_budget_label": "投入总预算 (USD)",
        "myr_budget_label": "投入总预算 (MYR)",
        "buy_price_label": "打算进场的价格 (USD)",
        "quantity_label": "最终确认购买股数",
        "max_quantity_hint": "最多可买",
        "percent_title": "🎯 战术百分比 (%) 设定",
        "profit_slider": "📈 基准获利目标 (%)",
        "stoploss_slider": "📉 基准止损底线 (%)",
        "take_profit_header": "获利剧本 (Take Profit)",
        "stop_loss_header": "防御剧本 (Stop Loss)",
        "scheme_a": "A 方案: 保守",
        "scheme_b": "B 方案: 达标",
        "scheme_c": "C 方案: 延伸",
        "stop_a": "A 方案: 撤退",
        "stop_b": "B 方案: 标准",
        "stop_c": "C 方案: 极限",
        "target_price": "目标价",
        "trigger_price": "触发价",
        "net_profit": "净赚",
        "net_loss": "净亏",
        "budget_warning": "⚠️ 预算不足以购买 1 股并支付手续费。",
        "quote_time": "⏱️ 报价时间: {}",
        "execution_title": "实行数据：",
        "input_label": "投入：",
        "purchase_label": "购买 ：",
        "remaining_label": "剩余资金:",
        "disclaimer": "**免责声明**：本工具
